services:
  frontend:
    image: ghcr.io/maksimovyuriy/artfolio-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs/artfolio.crt:/etc/nginx/certs/artfolio.crt:ro
      - ./certs/artfolio.key:/etc/nginx/certs/artfolio.key:ro
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25
    depends_on:
      - backend
  
  backend:
    image: ghcr.io/maksimovyuriy/artfolio-backend:latest
    env_file:
      - .env
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: ghcr.io/maksimovyuriy/artfolio-backend:latest
    command: ["./artfolio-migrate"]
    env_file:
      - .env
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-trixie
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 3s
      timeout: 3s
      retries: 5
    shm_size: 128mb
    mem_limit: 128m
    cpus: 0.25

  key:
    image: ghcr.io/maksimovyuriy/artfolio-backend:latest
    command: ["./artfolio-key"]
    env_file:
      - .env
    profiles:
      - tools
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
